import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import NavbarMain from "@/components/navbar/NavbarMain";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Example Project</title>
        <meta name="description" content={""} />
      </Head>
      <body className={`antialiased bg-slate-900 text-slate-400`}>
        <div className="flex flex-col min-h-screen">
          <NavbarMain />

          <main className="flex-grow flex flex-col items-center px-10 w-full">
            <div className="w-full">{children}</div>
          </main>

          <footer className="bg-slate-950 w-full py-4 flex justify-center">
            <div className="text-slate-500">Copyright by Humlek Co. Inc</div>
          </footer>
        </div>
      </body>
    </html>
  );
}
